[package]
name = "libsug"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.29"
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
dotenv = "0.15"
regex = "1.11.1"
